export var AMX_COMPACTMARGIN = 64;
export var AMX_CELL_SIZE = 4;
export var AMX_FLAG_COMPACT = 0x04;
export var AMX_EXEC_MAIN = -1;
export var AMX_EXEC_CONT = -2;
export var AMX_MAGIC = 0xf1e0;
export var AMX_CUR_FILE_VERSION = 10;
export var AMX_MIN_FILE_VERSION = 6;
export var AMX_MIN_AMX_VERSION = 8;
export var BYTE_SIZE = 56;
export var SIZEOF_FUNCSTUB = 20;
export var SIZEOF_FUNCSTUBNT = 8;
//# sourceMappingURL=constants.js.map